/**
 * Import các icon bạn cần sử dụng từ Element Plus
 * Lưu ý: Bạn sẽ cần import và đăng ký chúng trong SideBar.vue
 * hoặc sử dụng một cách tiếp cận linh hoạt hơn nếu số lượng icon lớn
 * Đối với ví dụ này, chúng ta chỉ cần tên của component icon
 * import { ChatDotRound, Timer, TrendCharts, OfficeBuilding, Box, DataAnalysis, Cpu, ShoppingTrolley } from "@element-plus/icons-vue";
 */

const MENU_ITEMS = [
  {
    name: "summary-dashboard",
    label: "Dashboard",
    iconComponent: "Histogram",
    routeName: "SummaryDashboard",
    isActive: false,
  },
  {
    name: "KHTC",
    label: "Kế hoạch tổ chức",
    iconComponent: "UserFilled",
    routeName: null,
    isActive: false,
    isDropdown: true,
    children: [
      {
        name: "time-tracking",
        label: "Quản lý chấm công",
        iconComponent: "List",
        routeName: "TimeTracking",
        isActive: false,
      },
    ]
  },
  // MESX
  {
    name: "WorkShop",
    label: "Work Shop",
    iconComponent: "OfficeBuilding",
    routeName: "WorkShop",
    isActive: false,
    isDropdown: true,
    children: [
      {
        name: "MESXDashboard",
        label: "Work Shop Dashboard",
        routeName: "MESXDashboard",
        iconComponent: "Platform",
        isActive: false,
      },
      {
        name: "ThongTinSanXuat",
        label: "Thông tin sản xuất",
        routeName: null,
        isDropdown: true,
        iconComponent: "Files",
        children: [
          {
            name: "QuanLyCongDoanSX",
            label: "Quản lý công đoạn SX",
            routeName: "QuanLyCongDoanSX",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "QuanLyQuyTrinh",
            label: "Quản lý quy trình",
            routeName: "QuanLyQuyTrinh",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "DinhMucSanPham",
            label: "Định mức sản phẩm",
            routeName: "DinhMucSanPham",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "QuanLyNangLucThiCong",
            label: "Quản lý năng lực thi công",
            routeName: "QuanLyNangLucThiCong",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "QuyTrinh",
            label: "Quy trình",
            routeName: "QuyTrinh",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "QuanLySanXuat",
        label: "Quản lý sản xuất",
        routeName: null,
        isDropdown: true,
        iconComponent: "Aim",
        children: [
          {
            name: "QuanLyOrder",
            label: "Quản lý order",
            routeName: "QuanLyOrder",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "KeHoachXuatHang",
            label: "Kế hoạch xuất hàng",
            routeName: "KeHoachXuatHang",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "KeHoachSanXuat",
            label: "Kế hoạch sản xuất",
            routeName: "KeHoachSanXuat",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "KeHoachSanXuatNgay",
            label: "Kế hoạch sản xuất ngày",
            routeName: "KeHoachSanXuatNgay",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "ChiThiSanXuat",
            label: "Chỉ thị sản xuất",
            routeName: "ChiThiSanXuat",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "TinhTrangTonKho",
            label: "Tình trạng tồn kho",
            routeName: "TinhTrangTonKho",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "SanXuat",
        label: "Sản xuất",
        routeName: null,
        isDropdown: true,
        iconComponent: "Tickets",
        children: [
          {
            name: "YeuCauXuatLinhKienNVL",
            label: "Yêu cầu xuất linh kiện/NVL",
            routeName: "YeuCauXuatLinhKienNVL",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "YeuCauNhapKhoThanhPham",
            label: "Yêu cầu nhập kho thành phẩm",
            routeName: "YeuCauNhapKhoThanhPham",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "YeuCauTraLinhKienNVL",
            label: "Yêu cầu trả linh kiện/NVL",
            routeName: "YeuCauTraLinhKienNVL",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "QuanLyThucThiSanXuat",
        label: "Quản lý thực thi sản xuất",
        routeName: null,
        isDropdown: true,
        iconComponent: "Tickets",
        children: [
          {
            name: "CapNhatTienDo",
            label: "Cập nhật tiến độ",
            routeName: "CapNhatTienDo",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "ChuyenGiaCongDoan",
            label: "Chuyển gia công đoạn",
            routeName: "ChuyenGiaCongDoan",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "LichSuGiaoDich",
            label: "Lịch sử giao dịch",
            routeName: "LichSuGiaoDich",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "ThongKeBaoCao",
        label: "Thống kê, báo cáo",
        routeName: null,
        isDropdown: true,
        iconComponent: "Tickets",
        children: [
          {
            name: "BaoCaoSanXuatHangNgay",
            label: "Báo cáo sản xuất hàng ngày",
            routeName: "BaoCaoSanXuatHangNgay",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoVeTienDoSanXuat",
            label: "Báo cáo về tiến độ sản xuất",
            routeName: "BaoCaoVeTienDoSanXuat",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoChatLuong",
            label: "Báo cáo chất lượng",
            routeName: "BaoCaoChatLuongQMSX",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoVeTieuHaoNVL",
            label: "Báo cáo về tiêu hao NVL",
            routeName: "BaoCaoVeTieuHaoNVL",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoChiTietTienDo",
            label: "Báo cáo chi tiết tiến độ",
            routeName: "BaoCaoChiTietTienDo",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoVeChiPhi",
            label: "Báo cáo về chi phí",
            routeName: "BaoCaoVeChiPhi",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoNangXuat",
            label: "Báo cáo năng xuất",
            routeName: "BaoCaoNangXuat",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoQuyetToanNhapXuatTonKhoNguyenLieuVatTu",
            label: "Báo cáo quyết toán nhập - xuất - tồn kho nguyên liệu, vật tư",
            routeName: "BaoCaoQuyetToanNhapXuatTonKhoNguyenLieuVatTu",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "BaoCaoTongHopDonHang",
            label: "Báo cáo tổng hợp đơn hàng",
            routeName: "BaoCaoTongHopDonHang",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "HanhChinhNhanSu",
        label: "Hành chính nhân sự",
        routeName: null,
        isDropdown: true,
        iconComponent: "Tickets",
        children: [
          {
            name: "KhaiBaoBacTayNghe",
            label: "Khai báo bậc tay nghề",
            routeName: "KhaiBaoBacTayNghe",
            iconComponent: "BottomRight",
            isActive: false,
          },
          {
            name: "QuanLyNhanVien",
            label: "Quản lý nhân viên",
            routeName: "QuanLyNhanVien",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
      {
        name: "ThietLap",
        label: "Thiết lập",
        routeName: null,
        isDropdown: true,
        iconComponent: "Tools",
        children: [
          {
            name: "ThietLapLichLamViec",
            label: "Thiết lập lịch làm việc",
            routeName: "ThietLapLichLamViec",
            iconComponent: "BottomRight",
            isActive: false,
          },
        ],
      },
    ],
  },
  // WMSX
  // {
  //   name: "WMSX",
  //   label: "WMSX",
  //   iconComponent: "Box",
  //   routeName: "WMSX",
  //   isActive: false,
  //   isDropdown: true,
  //   children: [
  //     {
  //       name: "WMSXDashboard",
  //       label: "Dashboard",
  //       routeName: "WMSXDashboard",
  //       iconComponent: "Platform",
  //       isActive: false,
  //     },
  //     {
  //       name: "ThietLapKho",
  //       label: "Thiết lập kho",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Coordinate",
  //       children: [
  //         {
  //           name: "QuanLyNhomKho",
  //           label: "Quản lý nhóm kho",
  //           routeName: "QuanLyNhomKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyKho",
  //           label: "Quản lý kho",
  //           routeName: "QuanLyKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyLayoutMau",
  //           label: "Quản lý layout mẫu",
  //           routeName: "QuanLyLayoutMau",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyViTri",
  //           label: "Quản lý vị trí",
  //           routeName: "QuanLyViTri",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LayoutKho",
  //           label: "Layout kho",
  //           routeName: "LayoutKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "QuanLyYeuCauWMSX",
  //       label: "Quản lý yêu cầu",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Aim",
  //       children: [
  //         {
  //           name: "YeuCauNhapKho",
  //           label: "Yêu cầu nhập kho",
  //           routeName: "YeuCauNhapKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "YeuCauXuatKho",
  //           label: "Yêu cầu xuất kho",
  //           routeName: "YeuCauXuatKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "QuanLyLenhPhieu",
  //       label: "Quản lý lệnh, phiếu",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Ticket",
  //       children: [
  //         {
  //           name: "PhieuNhapKho",
  //           label: "Phiếu nhập kho",
  //           routeName: "PhieuNhapKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "PhieuXuatKho",
  //           label: "Phiếu xuất kho",
  //           routeName: "PhieuXuatKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "CatHang",
  //           label: "Cất hàng",
  //           routeName: "CatHang",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LayHang",
  //           label: "Lấy hàng",
  //           routeName: "LayHang",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LenhKiemKe",
  //           label: "Lệnh kiểm kê",
  //           routeName: "LenhKiemKe",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "QuanLyTonKho",
  //       label: "Quản lý tồn kho",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Box",
  //       children: [
  //         {
  //           name: "TraCuuTonKho",
  //           label: "Tra cứu tồn kho",
  //           routeName: "TraCuuTonKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LenhKiemKeTonKho",
  //           label: "Lệnh kiểm kê",
  //           routeName: "LenhKiemKeTonKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeQuaHanSuDung",
  //           label: "Thống kê quá hạn sử dụng",
  //           routeName: "ThongKeQuaHanSuDung",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeQuaHanLuuKho",
  //           label: "ThongKeQuaHanLuuKho",
  //           routeName: "ThongKeQuaHanLuuKho",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "XuatBaoCao",
  //           label: "Xuất báo cáo",
  //           routeName: "XuatBaoCao",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LichSuCatHang",
  //           label: "Lịch sử cất hàng",
  //           routeName: "LichSuCatHang",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "LichSuLayHang",
  //           label: "Lịch sử lấy hàng",
  //           routeName: "LichSuLayHang",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // // QMSX
  // {
  //   name: "QMSX",
  //   label: "QMSX",
  //   iconComponent: "DataAnalysis",
  //   routeName: "QMSX",
  //   isActive: false,
  //   isDropdown: true,
  //   children: [
  //     {
  //       name: "QMSXDashboard",
  //       label: "Dashboard",
  //       routeName: "QMSXDashboard",
  //       iconComponent: "Platform",
  //       isActive: false,
  //     },
  //     {
  //       name: "DuLieuCoSoQMSX",
  //       label: "Dữ liệu cơ sở",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Coin",
  //       children: [
  //         {
  //           name: "DinhNghiaNguyenNhan",
  //           label: "Định nghĩa nguyên nhân",
  //           routeName: "DinhNghiaNguyenNhan",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "DinhNghiaLoi",
  //           label: "Định nghĩa lỗi",
  //           routeName: "DinhNghiaLoi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "DinhNghiaNhomLoi",
  //           label: "Định nghĩa nhóm lỗi",
  //           routeName: "DinhNghiaNhomLoi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "DinhNghiaTieuChiDanhGia",
  //           label: "Định nghĩa tiêu chí đánh giá",
  //           routeName: "DinhNghiaTieuChiDanhGia",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "DinhNghiaMauPhieuDanhGia",
  //           label: "Định nghĩa mẫu phiếu đánh giá",
  //           routeName: "DinhNghiaMauPhieuDanhGia",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "KeHoachQC",
  //       label: "Kế hoạch QC",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Memo",
  //       children: [
  //         {
  //           name: "QuanLyYeuCauQC",
  //           label: "Quản lý yêu cầu QC",
  //           routeName: "QuanLyYeuCauQC",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyLenhQC",
  //           label: "Quản lý lệnh QC",
  //           routeName: "QuanLyLenhQC",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThucHienQC",
  //           label: "Thực hiện QC",
  //           routeName: "ThucHienQC",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "KiemSoatChatLuong",
  //       label: "Kiểm soát chất lượng",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Aim",
  //       children: [
  //         {
  //           name: "PhieuBaoCaoLoi",
  //           label: "Phiếu báo cáo lỗi",
  //           routeName: "PhieuBaoCaoLoi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "DeXuatXuLy",
  //           label: "Đề xuất xử lý",
  //           routeName: "DeXuatXuLy",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "PhanTichVaBaoCao",
  //       label: "Phân tích và báo cáo",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Reading",
  //       children: [
  //         {
  //           name: "BaoCaoChatLuong",
  //           label: "Báo cáo chất lượng",
  //           routeName: "BaoCaoChatLuongQMSX",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeTienDoQC",
  //           label: "Thống kê tiến độ QC",
  //           routeName: "ThongKeTienDoQC",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeTheoDonViYeuCau",
  //           label: "Thống kê theo đơn vị yêu cầu",
  //           routeName: "ThongKeTheoDonViYeuCau",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeTheoNguyenNhanLoi",
  //           label: "Thống kê theo nguyên nhân lỗi",
  //           routeName: "ThongKeTheoNguyenNhanLoi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // // MMSX
  // {
  //   name: "MMSX",
  //   label: "MMSX",
  //   iconComponent: "Cpu",
  //   routeName: "MMSX",
  //   isActive: false,
  //   isDropdown: true,
  //   children: [
  //     {
  //       name: "MMSXDashboard",
  //       label: "Dashboard",
  //       routeName: "MMSXDashboard",
  //       iconComponent: "Platform",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyThietBi",
  //       label: "Quản lý thiết bị",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Document",
  //       children: [
  //         {
  //           name: "QuanLyThongTinThietBi",
  //           label: "Quản lý thông tin thiết bị",
  //           routeName: "QuanLyThongTinThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyLayoutThietBi",
  //           label: "Quản lý layout thiết bị",
  //           routeName: "QuanLyLayoutThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyCayThietBi",
  //           label: "Quản lý cây thiết bị",
  //           routeName: "QuanLyCayThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyLoaiThietBi",
  //           label: "Quản lý loại thiết bị",
  //           routeName: "QuanLyLoaiThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyTrangThaiThietBi",
  //           label: "Quản lý trạng thái thiết bị",
  //           routeName: "QuanLyTrangThaiThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "QuanLyKeHoach",
  //       label: "Quản lý kế hoạch",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Menu",
  //       children: [
  //         {
  //           name: "QuanLyKeHoachBaoTri",
  //           label: "Quản lý kế hoạch bảo trì",
  //           routeName: "QuanLyKeHoachBaoTri",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyKeHoachLapDat",
  //           label: "Quản lý kế hoạch lắp đặt",
  //           routeName: "QuanLyKeHoachLapDat",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyKeHoachDuTru",
  //           label: "Quản lý kế hoạch dự trù",
  //           routeName: "QuanLyKeHoachDuTru",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "QuanLyMauPhieu",
  //       label: "Quản lý mẫu phiếu",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Document",
  //       children: [
  //         {
  //           name: "QuanLyMauPhieuMMSX",
  //           label: "Quản lý mẫu phiếu",
  //           routeName: "QuanLyMauPhieuMMSX",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyChecksheet",
  //           label: "Quản lý checksheet",
  //           routeName: "QuanLyChecksheet",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "CongViecBaoTri",
  //       label: "Công việc & Bảo trì",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Menu",
  //       children: [
  //         {
  //           name: "QuanLyDoiBaoTri",
  //           label: "Quản lý đội bảo trì",
  //           routeName: "QuanLyDoiBaoTri",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyCongViec",
  //           label: "Quản lý công việc",
  //           routeName: "QuanLyCongViec",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyCongViecCuaToi",
  //           label: "Quản lý công việc của tôi",
  //           routeName: "QuanLyCongViecCuaToi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "QuanLyCanhBao",
  //           label: "Quản lý cảnh báo",
  //           routeName: "QuanLyCanhBao",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "YeuCauXuLyBatThuong",
  //           label: "Yêu cầu xử lý bất thường",
  //           routeName: "YeuCauXuLyBatThuong",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //     {
  //       name: "BaoCaoMMSX",
  //       label: "Báo cáo",
  //       routeName: null,
  //       isDropdown: true,
  //       iconComponent: "Download",
  //       children: [
  //         {
  //           name: "BaoCaoTongHopTinhTrangSuDungThietBi",
  //           label: "Báo cáo tổng hợp tình trạng sử dụng thiết bị",
  //           routeName: "BaoCaoTongHopTinhTrangSuDungThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "TongHopKetQuaBaoTriThietBi",
  //           label: "Tổng hợp kết quả bảo trì thiết bị",
  //           routeName: "TongHopKetQuaBaoTriThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeXuLyBatThuongTheoThietBi",
  //           label: "Thống kê xử lý bất thường theo thiết bị",
  //           routeName: "ThongKeXuLyBatThuongTheoThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeThoiGianChayMay",
  //           label: "Thống kê thời gian chạy máy",
  //           routeName: "ThongKeThoiGianChayMay",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeCongViecBaoTriBaoDuongThietBi",
  //           label: "Thống kê công việc bảo trì, bảo dưỡng thiết bị",
  //           routeName: "ThongKeCongViecBaoTriBaoDuongThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "KeHoachBaoTriKiemTraThietBi",
  //           label: "Kế hoạch bảo trì & kiểm tra thiết bị",
  //           routeName: "KeHoachBaoTriKiemTraThietBi",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "ThongKeCongViecCuaNhanVien",
  //           label: "Thống kê công việc của nhân viên",
  //           routeName: "ThongKeCongViecCuaNhanVien",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //         {
  //           name: "BaoCaoMTTRMTBF",
  //           label: "Báo cáo MTTR & MTBF",
  //           routeName: "BaoCaoMTTRMTBF",
  //           iconComponent: "BottomRight",
  //           isActive: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // // PMSX
  // {
  //   name: "PMSX",
  //   label: "PMSX",
  //   iconComponent: "ShoppingTrolley",
  //   routeName: "PMSX",
  //   isActive: false,
  //   isDropdown: true,
  //   children: [
  //     {
  //       name: "PMSXDashboard",
  //       label: "Dashboard",
  //       routeName: "PMSXDashboard",
  //       iconComponent: "Platform",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyYeuCauMua",
  //       label: "Quản lý yêu cầu mua",
  //       routeName: "QuanLyYeuCauMua",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyKeHoachMuaHang",
  //       label: "Quản lý kế hoạch mua hàng",
  //       routeName: "QuanLyKeHoachMuaHang",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "DonMuaHangPO",
  //       label: "Đơn mua hàng (PO)",
  //       routeName: "DonMuaHangPO",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyHoaDonMuaHang",
  //       label: "Quản lý hóa đơn mua hàng",
  //       routeName: "QuanLyHoaDonMuaHang",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "NhaCungCap",
  //       label: "Nhà cung cấp",
  //       routeName: "NhaCungCap",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyBaoGia",
  //       label: "Quản lý báo giá",
  //       routeName: "QuanLyBaoGia",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "TieuChiDanhGiaNCC",
  //       label: "Tiêu chí đánh giá NCC",
  //       routeName: "TieuChiDanhGiaNCC",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //     {
  //       name: "QuanLyYeuCauBaoGia",
  //       label: "Quản lý yêu cầu báo giá",
  //       routeName: "QuanLyYeuCauBaoGia",
  //       iconComponent: "Compass",
  //       isActive: false,
  //     },
  //   ],
  // },
  {
    name: "chat",
    label: "Đoạn Chat",
    iconComponent: "ChatLineSquare",
    routeName: "Chat",
    isActive: false,
  },
];

export { MENU_ITEMS };